services:
  - type: web
    name: base
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./

  - type: web
    name: backend
    plan: free
    runtime: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: ./
    envVars:
      - key: NODE_ENV
        value: development
      - key: NX_DB_URL
        value: postgresql://${NX_DB_USER}:${NX_DB_PASSWORD}@db:${NX_DB_PORT}/${NX_DB_NAME}?sslmode=disable
      - key: NX_FRONTEND_HOST
        value: frontend
      - key: NX_JWT_SECRET
        value: ${NX_JWT_SECRET}
      - key: PORT
        value: '3000'
      - key: NX_FRONTEND_HOST
        value: ${NX_FRONTEND_HOST}

  - type: web
    name: frontend
    plan: free
    runtime: docker
    dockerfilePath: ./apps/frontend/Dockerfile
    dockerContext: ./
    envVars:
      - key: NX_BACKEND_HOST
        value: backend
      - key: PORT
        value: '4200'
      - key: NX_BACKEND_HOST
        value: ${NX_BACKEND_HOST}

databases:
  - name: db
    databaseName: NX_DB_NAME
    user: NX_DB_USER
    plan: free
    envVars:
      - key: NX_DB_NAME
        value: ${NX_DB_USER}
      - key: NX_DB_USER
        value: ${NX_DB_NAME}
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
