services:
  - type: web
    name: base
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./

  - type: web
    name: backend
    plan: free
    runtime: docker
    dockerfilePath: ./apps/backend/Dockerfile
    dockerContext: ./
    env:
      - key: NX_JWT_SECRET
        value: ${NX_JWT_SECRET}
      - key: PORT
        value: '3000'
      - key: NX_FRONTEND_HOST
        value: ${NX_FRONTEND_HOST}

  - type: web
    name: frontend
    plan: free
    runtime: docker
    dockerfilePath: ./apps/frontend/Dockerfile
    dockerContext: ./
    env:
      - key: PORT
        value: '4200'
      - key: NX_BACKEND_HOST
        value: ${NX_BACKEND_HOST}

databases:
  - name: db
    databaseName: ${NX_DB_NAME}
    user: ${NX_DB_USER}
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
